#!/bin/bash
# rawdata-procedures - Camera raw data procedures
#
# Copyright (c) 2013-2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Kevin Velickovic <k.velickovic@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

# Script parameters #
PARAM_MOUNT="/data/"
PARAM_MAC=""
PARAM_MASTER=""
PARAM_SEGMENT=""
PARAM_DISK_THREADS=""

# Loop breaker
LOOP_BREAK="0"

# Help function
_help() {
    echo """
    Usage: $(basename $0) [OPTIONS]

    [Required arguments]
    --mount-point       Base mount directory
    --mac-address       Camera MAC address
    --master-timestamp  Master timestamp

    [Optional arguments]
    --segment-timestamp Segment timestamp
    --disk-threads      Process localy with specified number of threads
    --help              Show this message
    """
}

# Trap ctrl-c and call ctrl_c()
trap ctrl_c INT

# CTRL-C handler function
function ctrl_c() {

    # Set loop break flag
    LOOP_BREAK="1"
}

# Arguments and parameters parser
arguments() {

    # Search in arguments
    while [[ $# > 0 ]]; do

        args="$1"
        shift
        case $args in
            --mount-point)
                PARAM_MOUNT="$1"
                shift
            ;;
            --mac-address)
                PARAM_MAC="$1"
                shift
            ;;
            --master-timestamp)
                PARAM_MASTER="$1"
                shift
            ;;
            --segment-timestamp)
                PARAM_SEGMENT="$1"
                shift
            ;;
            --disk-threads)
                if [ -z "$1" ]; then
                    PARAM_DISK_THREADS="+0"
                else
                    PARAM_DISK_THREADS="$1"
                fi
                shift
            ;;
            --help | -h)
                _help
                exit
            ;;
        esac

    done

}

if [ $# -eq 0 ]; then
    _help
    exit
fi

# Argument and parameters #
arguments $@

# Check execution consistency #
if [ -z "$PARAM_MOUNT" ] || [ -z "$PARAM_MAC" ] || [ -z "$PARAM_MASTER" ]; then

    # Exit script #
    echo "Error : cannot continue execution without --mount-point/--mac-address/--master-timestamp parameters"
    exit 1

fi

# Check execution consistency #
if [ ! -d $PARAM_MOUNT/camera ]; then

    # Exit script #
    echo "Error : unable to access standard directory with specified mount point"
    exit 1

fi

# SSH configs cirectory
SSH_CONFIGS_DIR="$PARAM_MOUNT/system/etc/ssh-configs/rawdata-procedures"

# SSH config file
SSH_CONFIG_FILE="$SSH_CONFIGS_DIR/rawdata-movsplit.conf"

# Segments base folder
MASTER_DIR="$PARAM_MOUNT/rawdata/$PARAM_MAC/master/$PARAM_MASTER"

# Segments base folder
SEGMENTS_DIR="$MASTER_DIR/segment"

# Scripts paths
PARALLEL_SCRIPT="parallel"
SPLIT_SCRIPT="rawdata-movsplit-splitter"
JSONUPDATE_SCRIPT="rawdata-movsplit-jsonupdater"
STATE_SCRIPT="rawdata-movsplit-state"
LIST_SCRIPT="rawdata-movsplit-movlist"

# Check if a segment is specified
if [ -z "$PARAM_SEGMENT" ]; then

    # Check if master have segments
    if [ "$(ls -A $SEGMENTS_DIR)" ]; then

        # Iterate over segments
        for d in $SEGMENTS_DIR/* ; do

            # Determine segment folder
            SEGMENT_TIMESTAMP=$(basename $d)
            SEGMENT_FOLDER=$SEGMENTS_DIR/$SEGMENT_TIMESTAMP

            # Check if segment is already splitted
            $STATE_SCRIPT $PARAM_MOUNT \
            $PARAM_MAC \
            $PARAM_MASTER \
            $SEGMENT_TIMESTAMP

            if [ $? -eq 1 ]; then
                >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Segment $SEGMENT_TIMESTAMP already splitted, skipping"
            else

                # Build MOV list
                MOV_LIST="$(
                    $LIST_SCRIPT \
                    $PARAM_MOUNT \
                    $PARAM_MAC \
                    $PARAM_MASTER \
                    $SEGMENT_TIMESTAMP | sort
                )"

                # Check MOV list length
                if [ ${#MOV_LIST} -gt 0 ]; then

                    # Split segment
                    >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Splitting segment $SEGMENT_TIMESTAMP..."

                    if [ -z "$PARAM_DISK_THREADS" ]; then
                        echo "$MOV_LIST" | $PARALLEL_SCRIPT --gnu --retries 5 --will-cite --eta --ungroup --sshloginfile $SSH_CONFIG_FILE $SPLIT_SCRIPT {} \
                        $PARAM_MOUNT \
                        $PARAM_MAC \
                        $PARAM_MASTER \
                        $SEGMENT_TIMESTAMP
                    else
                        echo "$MOV_LIST" | $PARALLEL_SCRIPT --gnu --retries 5 --will-cite --eta -j$PARAM_DISK_THREADS $SPLIT_SCRIPT {} \
                        $PARAM_MOUNT \
                        $PARAM_MAC \
                        $PARAM_MASTER \
                        $SEGMENT_TIMESTAMP
                    fi

                    # Loop break checker
                    if [ $LOOP_BREAK -ne 0 ]; then break; fi

                    # Update JSON file
                    >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Updating segment JSON file..."
                    $JSONUPDATE_SCRIPT $PARAM_MOUNT \
                    $PARAM_MAC \
                    $PARAM_MASTER \
                    $SEGMENT_TIMESTAMP

                else

                    # Display warning
                    >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Segment $SEGMENT_TIMESTAMP have no MOV files, skipping"
                fi
            fi
        done
    else

        # Display warning
        >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Master $PARAM_MASTER have no segments, skipping"
    fi

else

    # Determine segment folder
    SEGMENT_FOLDER=$SEGMENTS_DIR/$PARAM_SEGMENT

    # Check if segment is already splitted
    $STATE_SCRIPT $PARAM_MOUNT \
    $PARAM_MAC \
    $PARAM_MASTER \
    $PARAM_SEGMENT

    if [ $? -eq 1 ]; then
        >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Segment $PARAM_SEGMENT already splitted, skipping"
    else

        # Build MOV list
        MOV_LIST="$(
            $LIST_SCRIPT \
            $PARAM_MOUNT \
            $PARAM_MAC \
            $PARAM_MASTER \
            $PARAM_SEGMENT  | sort
        )"

        # Check MOV list length
        if [ ${#MOV_LIST} -gt 0 ]; then

            # Split segment
            >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Splitting segment $PARAM_SEGMENT..."

            if [ -z "$PARAM_DISK_THREADS" ]; then
                echo "$MOV_LIST" | $PARALLEL_SCRIPT --gnu --retries 5 --will-cite --eta --ungroup --sshloginfile $SSH_CONFIG_FILE $SPLIT_SCRIPT {} \
                $PARAM_MOUNT \
                $PARAM_MAC \
                $PARAM_MASTER \
                $PARAM_SEGMENT
            else
                echo "$MOV_LIST" | $PARALLEL_SCRIPT --gnu --retries 5 --will-cite --eta -j$PARAM_DISK_THREADS $SPLIT_SCRIPT {} \
                $PARAM_MOUNT \
                $PARAM_MAC \
                $PARAM_MASTER \
                $PARAM_SEGMENT
            fi

            # Loop break checker
            if [ $LOOP_BREAK -ne 0 ]; then break; fi


            # Update JSON file
            >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Updating segment JSON file..."
            $JSONUPDATE_SCRIPT $PARAM_MOUNT \
            $PARAM_MAC \
            $PARAM_MASTER \
            $PARAM_SEGMENT

        else

            # Display warning segment
            >&2 echo "[$(date '+%F %R')] rawdata-movsplit : Segment $SEGMENT_TIMESTAMP have no MOV files, skipping"
        fi
    fi

fi
