#!/bin/bash
# rawdata-procedures - Camera raw data procedures 
#
# Copyright (c) 2013-2014 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Nils Hamel <n.hamel@foxel.ch>
#       Alexandre Kraft <a.kraft@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

# Script execution switch #
SWITCH_DOWNLOAD=""
SWITCH_NOSPLIT="FALSE"
SWITCH_NOPREVIEW="FALSE"
SWITCH_NODEBAYER="FALSE"

# Script parameters #
PARAM_MOUNT="/data/"
PARAM_MAC=""
PARAM_MASTER=""
PARAM_SEGMENT=""

# Arguments and parameters parser #
arguments() {

    # Search in arguments #
    for args in "$@"; do

        case $args in
            --download*)
                SWITCH_DOWNLOAD="TRUE"
            ;;
            --no-split*)
                SWITCH_NOSPLIT="TRUE"
            ;;
            --no-preview*)
                SWITCH_NOPREVIEW="TRUE"
            ;;
            --no-debayer*)
                SWITCH_NODEBAYER="TRUE"
            ;;
            --mount-point*)
                PARAM_MOUNT="${args#*=}"
                shift
            ;;
            --mount-point*)
                PARAM_MOUNT="${args#*=}"
                shift
            ;;
            --mac-address*)
                PARAM_MAC="${args#*=}"
                shift
            ;;
            --master-timestamp*)
                PARAM_MASTER="${args#*=}"
                shift
            ;;
            --segment-timestamp*)
                PARAM_SEGMENT="${args#*=}"
                shift
            ;;
        esac

    done

}

# Argument and parameters #
arguments $@

echo "$SWITCH_DOWNLOAD"

# Check execution consitency #
if [ "$SWITCH_DOWNLOAD" == "TRUE" ] && [ -z "$PARAM_MAC" ] && [ -z "$PARAM_MASTER" ] && [ -z "$PARAM_SEGMENT" ]; then

    # Run procedure #
    echo "rawdata-procedures : downloading raw data ..."
    echo "rawdata-???"

    # Run procedure #
    echo "rawdata-procedures : moving downloaded raw data ..."
    echo "rawdata-???"

    # Temporary #
    RETURN="AA:BB:CC:DD:EE:FF 123768762"

    # Extract returned value - MAC address and master timestamp #
    PARAM_MAC=`echo $RETURN| cut -d'_' -f 1`
    PARAM_MASTER=`echo $RETURN| cut -d'_' -f 2`


else

    # Display wrong usage #
    echo "Error : unable to understand --download switch with --mac-address/--master-timestamp/--segment-timestamp parameters"

fi

echo $PARAM_MAC
echo $PARAM_MASTER

# Check execution consistency #
if [ -n "$PARAM_MAC" ] && [ -n "$PARAM_MASTER" ]; then

    # Run procedure #
    echo "rawdata-procedures : auto-segmentation ..."
    echo "rawdata-autoseg $PARAM_MOUNT $PARAM_MAC $PARAM_MASTER"

    # Run procedure #
    echo "rawdata-procedures : splitting table of mov files ..."
    echo "rawdata-???"

    # Run procedure #
    echo "rawdata-procedures : hard-linking of mov files ..."
    echo "rawdata-???"

    # Check execution switch #
    if [ "$SWITCH_NOSPLIT" == "TRUE" ]; then exit 0; fi

    # Run procedure #
    echo "rawdata-procedures : splitting of mov files ..."
    echo "rawdata-???"

    # Check execution switch #
    if [ "$SWITCH_NOPREVIEW" == "TRUE" ]; then exit 0; fi

    # Run procedure #
    echo "rawdata-procedures : image previews ..."
    echo "rawdata-???"

else

    # Display wrong usage #
    echo "Error : cannot continue exectution without --mac-address/--master-timestamp parameters"

fi

