
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-dbpusher bin/rawdata-dbpusher

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
