
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-downloader-eyesis bin/rawdata-downloader-eyesis
	cp src/rawdata-downloader-snapshot bin/rawdata-downloader-snapshot

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
