
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-movsplit bin/rawdata-movsplit

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
