
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-autoseg bin/rawdata-autoseg

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
