#!/bin/bash
# rawdata-procedures - Camera raw data procedures
#
# Copyright (c) 2015 FOXEL SA - http://foxel.ch
# Please read <http://foxel.ch/license> for more information.
#
#
# Author(s):
#
#       Kevin Velickovic <k.velickovic@foxel.ch>
#
#
# This file is part of the FOXEL project <http://foxel.ch>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Additional Terms:
#
#       You are required to preserve legal notices and author attributions in
#       that material or in the Appropriate Legal Notices displayed by works
#       containing it.
#
#       You are required to attribute the work as explained in the "Usage and
#       Attribution" section of <http://foxel.ch/license>.

HOST_NAME="$USER@$HOSTNAME"

# Check rawdata-movsplit
if ! which rawdata-movsplit >/dev/null; then

    # Debug output
    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $HOST_NAME : rawdata-movsplit not installed"

    # Flag error
    ENV_NOT_OK="1"

fi

# Check rawdata-movsplit-jsonupdater
if ! which rawdata-movsplit-jsonupdater >/dev/null; then

    # Debug output
    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $HOST_NAME : rawdata-movsplit-jsonupdater not installed"

    # Flag error
    ENV_NOT_OK="1"

fi

# Check rawdata-movsplit-movlist
if ! which rawdata-movsplit-movlist >/dev/null; then

    # Debug output
    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $HOST_NAME : rawdata-movsplit-movlist not installed"

    # Flag error
    ENV_NOT_OK="1"

fi

# Check ImageMagick
if ! which rawdata-movsplit-splitter >/dev/null; then

    # Debug output
    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $HOST_NAME : rawdata-movsplit-splitter not installed"

    # Flag error
    ENV_NOT_OK="1"

fi

# Check ImageMagick
if ! which rawdata-movsplit-state >/dev/null; then

    # Debug output
    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $HOST_NAME : rawdata-movsplit-state not installed"

    # Flag error
    ENV_NOT_OK="1"

fi

if [ ! -z "$ENV_NOT_OK" ]; then
    exit 1
fi
