
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-dependencies bin/rawdata-dependencies
	cp src/scripts/rawdata-dependencies-checker bin/rawdata-dependencies-checker
	cp src/scripts/rawdata-dependencies-checker-split bin/rawdata-dependencies-checker-split
#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
