
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-jp4preview bin/rawdata-jp4preview
	cp src/scripts/* bin/

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
