
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-jp4table bin/rawdata-jp4table

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
