
#
#   make - synchronize
#

    all:directories
	cp src/rawdata-jp4trasher bin/rawdata-jp4trasher

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
